### ISSUE TITLE
Wrong name and property of observed data from Cox 1986

### ISSUE THREAD

**Issue by sfrechen** [Open-Systems-Pharmacology/Cimetidine-Model#2]
Drug was administered via intraduodenal infusion.

Respective data contain "IV" -> needs to be renamed:

Cox 1986 - triazolam control - Triazolam - IV - 0.5 mg - Serum - agg. (n=4)

Respective data have meta property: "Route: IV". Needs to be corrected as well.

**Comment by sfrechen** [comment]
@TWendl

**Comment by TWendl** [comment]
not necessary in cimetidine model as these data are not included there.
