### ISSUE TITLE
Cimetidine Model Evaluation Report does actually not list the Hanke 2020 Ref in the REF LIst

### ISSUE THREAD

**Issue by StephanSchaller** [Open-Systems-Pharmacology/Cimetidine-Model#5]
Cimetidine Model Evaluation Report does actually not list the Hanke 2020 Ref in the REF LIst

**Comment by Yuri05** [comment]
@TWendl This is fixed with the last PR, correct?

**Comment by Yuri05** [comment]
is fixed
